version: '2.1'
services:
  nginx:
    depends_on:
      - almondchocolate
    image: rockplace/nginx
    links:
      - almondchocolate:almondchocolate
    ports:
      - "80:80"
  almondchocolate:
    depends_on:
      - db
    image: almond_chocolate:latest
    links:
      - db:db
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=rplinux
      - MYSQL_DATABASE=new_almond
      - MYSQL_USER=almond
      - MYSQL_PASSWORD=rplinux
      - MYSQL_CHARSET=utf8
    volumes:
      - mysql-data:/var/lib/mysql    
volumes:
  mysql-data: